### ISSUE TITLE
Coroutines fail to run on iOS with RoboVM

### ISSUE THREAD

**Issue by auraxangelic** [libktx/ktx#350]
I'm hoping to get some help with the use of async on iOS. I'm not sure if it's a bug, or if it's my setup, or if async is even meant to work on iOS. 

When using versions 1.9.13 of libGDX, 1.9.13-b1 of KTX, 1.4.2 of kotlinx-coroutines-core, the app compiles fine, but I see the following runtime error when I try to call the `KtxAsync.initiate()` function in `Game#create()`.
> java.lang.NoClassDefFoundError: ktx/async/KtxAsync

When using versions 1.9.14 of libGDX and 1.9.14-b1 of KTX, I get 58 duplicate symbols error due to underscore and dot versions in the packages and fails to compile the app.
> libgdx.a(com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.o)
> libgdx.a(com_badlogic_gdx_graphics_g2d_Gdx2dPixmap.o)

The issue in 1.9.14 is probably due to this: https://github.com/libgdx/libgdx/issues/6437 and not a KTX issue.

More versions:
- Kotlin: 1.4.+
- Robovm: 2.3.11
- Kotlinx-coroutines-core: 1.4.2

Please let me know if you have any ideas of about getting async working on iOS.

**Comment by czyzby** [comment]
It should work on all platform, but unfortunately we're not running automated tests on iOS. One user had a similar error in one of the utility functions (see #204). In this case, JVM target was not set to 1.6, which I'm guessing caused some classes to fail to load. Right now [all of the KTX modules are set to target 1.6](https://github.com/libktx/ktx/blob/1.9.14-b1/build.gradle.kts#L78-L88), so as far as I can tell it could be your setup or Kotlin compiler outputs something incompatible with LibGDX iOS backend.

Can you try specifying JVM target version in your Gradle setup? If that doesn't help, you could try copying `ktx-async` sources into your application to see if you encounter any issues during compilation.

**Comment by czyzby** [comment]
If for some reason RoboVM has a problem with `KtxAsync` class in particular, you could try calling `MainDispatcher.initiate()` instead to initiate the coroutines and see if you can launch a coroutine with the `MainDispatcher` in the first place. You'll probably encounter other issues further down the line when using modules like `ktx-assets-async`, but at least it would allow us to pinpoint the problem.

**Comment by auraxangelic** [comment]
When I switch to target 1.6, I get `error: Source option 6 is no longer supported. User 7 or later.` I assume this is due to my gradle version. I assume this is due to my gradle version. My target is 8.0.

Couple questions:
- Are there any issues with using the async from master with 1.9.13 libGDX?
- Can you please show me how I would launch a coroutine with `MainDispatcher`?

**Comment by czyzby** [comment]
> When I switch to target 1.6, I get `error: Source option 6 is no longer supported. User 7 or later.` I assume this is due to my gradle version. My target is 8.0.

Probably, yeah. You could try downgrading to a previous version of Gradle just to check if that's causing the issue.

> Are there any issues with using the async from master with 1.9.13 libGDX?

There shouldn't be. `ktx-async` barely relies on LibGDX APIs either way, so you should get away with using the newer KTX version and an older LibGDX.

> Can you please show me how I would launch a coroutine with `MainDispatcher`?

```kotlin
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.launch
import ktx.async.MainDispatcher

fun launchCoroutines() {
  // Initiating dispatcher on the main rendering thread:
  MainDispatcher.initiate()
  
  GlobalScope.launch(MainDispatcher) {
    // Executed on the rendering thread.
  }
}
```
But like I've said, you'll probably encounter issues further down the line.

In fact, it might be worth it to check if coroutines work at all:

```kotlin
GlobalScope.launch { 
  println("Executed via coroutine")
}
```

**Comment by auraxangelic** [comment]
I've actually tried regular coroutines with `GlobalScope` and I get the same `ClassDefNotFoundError` with the GlobalScope class. It's like Robovm tries to repel anything that has to do with coroutines.

**Comment by czyzby** [comment]
@auraxangelic Can you try to downgrade the Gradle version and set the source target to 1.6? Thanks.

**Comment by czyzby** [comment]
Actually, it might be the JDK version rather than Gradle. You might need to compile your application with an older JDK like 1.8 or 1.11. Not sure if that's the source of the issue, but I have no other ideas how you could get around that error at the moment. Sorry.

**Comment by auraxangelic** [comment]
I'm currently using 11.0.9 for the JDK. Also KtxAsync works with no problems on desktop and android. Really weird issue.

I'm going to side-step this issue for now and use the AsyncExecutor. The structure ends up being similar in Kotlin. Create a global AsyncExecutor and go `asyncExecuter.submit{}` instead of `KtxAsync.launch/async{}`.

It doesn't have as many nice features as KtxAsync, but the AsyncExecutor is working for me right now.

It would be interesting to see why Robovm isn't picking up coroutines though.

**Comment by czyzby** [comment]
Yeah, the purpose of `AsyncExecutor`is a bit different, but if all you need is to execute some code on a different thread, it should be enough.

@auraxangelic Have you tried to compile the code with 1.6 target just to see if it helps? I'm unable to test this myself at this moment, and I'm curious whether coroutines simply do not work on iOS and there's no way around it or if it's a matter of configuration. You can also try downgrading to an older `kotlinx.coroutines` - I think the lack of support for 1.6 is a pretty recent thing in Gradle/JDK, so chances are a previous version of coroutines might be compatible with iOS.

**Comment by auraxangelic** [comment]
I managed to create a new libGDX project, ensured it worked on iOS, added KtxAsync, switched source and target compatibility to 1.6 and compiled it for iOS. I get the following runtime error:
`java.lang.NoClassDefFoundError: kotlin.coroutines.CoroutineScope`

It was able to pick up KtxAsync, but it still looks like RoboVM still does not like kotlinx.

**Comment by czyzby** [comment]
@auraxangelic I see. It's possible that the coroutines version is not compatible with RoboVM. If you don't mind and have some time, I'd appreciate it if you went through [older versions](https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-core) of `kotlinx.coroutines` and see if they work correctly. If not, I guess there's not much we can do on our side and I'll just document this in the README.

**Comment by auraxangelic** [comment]
Regular coroutines definitely don't work. Still a `NoClassDefFoundError` on `GlobalScope`. This is actually the case for a lot of classes. Most recently, I had this issue with `java.util.Base64`. You'd think RoboVM would pick that up, but no. Instead you have to use `com.badlogic.gdx.utils.Base64Coder`.

I assume there was a point where KtxAsync worked at some point. If so, I would love to replicate that environment. If you have any hints as to what that environment is, that would be extremely helpful.

Any of these data points would be useful:
- Last known working RoboVM version on iOS for ktx-async
- Last known working ktx-async version on iOS
- Last known working time (could check RoboVM release versions by the time)

**Comment by czyzby** [comment]
Personally I haven't tested coroutines module on iOS, only on desktop and Android. However, I know for a fact that there are some KTX games in the app store. It's definitely more of a Kotlin/RoboVM issue than KTX, and I don't think there's anything we can do on our side other than document the problems and try to find a compatible configuration. I'm not sure if anyone managed to use `ktx-async` on iOS either. [It seems like at least at some point coroutines worked with RoboVM](https://github.com/MobiVM/robovm/issues/220), as people were getting unrelated errors.

`KtxAsync` no longer throwing exceptions is a step in the right direction, and wrong target level might be the root cause of the issue. My guess is that `kotlinx.coroutines` are no longer compatible with 1.6, which causes the error even with plain coroutines. If you have the time to do this, please go through the `kotlinx.coroutines` version up to, let's say, `1.1.x`. Use the latest RoboVM version and try to launch any coroutine with the `GlobalScope`.

If you manage to do this, you can also check if it's compatible with `ktx-async`. If it isn't, let me know and we'll think of something - I'm not against downgrading the library version or maintaining a separate module for a while until RoboVM catches up.

I'd love to automate that and make sure that all of the modules are compatible with Android and RoboVM, but I'm not sure if it would be easy to set up with GitHub actions, especially since we're using desktop-specific code in tests. I might create a separate  issue to look into that.

**Comment by czyzby** [comment]
@auraxangelic Did you have a chance to check if any legacy coroutines version works with 1.6 source level on iOS? I want to update `ktx-async` documentation, or even freeze the version to support all platforms. If you have some time to test this, I'd appreciate it. Thanks.

**Comment by auraxangelic** [comment]
Heya! I've tried down to 1.3.8 because that's the oldest one on maven 'https://search.maven.org/search?q=g:org.jetbrains.kotlinx%20a:kotlinx-coroutines*'  and I still experience this issue.

It's definitely a RoboVM issue, and not a KTX specific issue. Regular coroutines just don't seem to work on iOS with a NoClassDefFoundError on anything kotlinx/coroutines related.

**Comment by czyzby** [comment]
> I've tried down to 1.3.8 because that's the oldest one on maven

I think older versions should be available via Maven Central as well - the search shows up there are [79 versions of the `kotlinx-coroutines-core` library](https://search.maven.org/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-core).

In the RoboVM issue that I've posted, I believe someone managed to run the 1.0.1 version of coroutines. Latest version of Kotlin at the time was around 1.3.11. @auraxangelic, coul you try to A) run plain 1.0.1 coroutines with latest Kotlin, or if it doesn't work for whatever reason B) downgrade both the coroutines and Kotlin version to see if it still works with the latest RoboVM? If this legacy version allows to use coroutines, at least we have a starting point.

> Also really annoying that it errors at runtime. There's no good way to check for this issue.

Maybe there are some warnings somewhere down the line. Seems like a major issue that should be reported, to be honest.

**Comment by czyzby** [comment]
@auraxangelic Could you also set up an issue in the [RoboVM repository](https://github.com/MobiVM/robovm/) with details about your setup and a complete stack trace? Downgrading the Kotlin or coroutines version is a workaround, this should be addressed on their side.

**Comment by auraxangelic** [comment]
I've just tested on 1.1.1 and 1.0.1, and I'm still seeing the same issue. RoboVM is definitely not picking up kotlin coroutines no matter which version.

**Comment by czyzby** [comment]
@auraxangelic Thanks, it might be an issue with RoboVM after all. The only thing I can suggest is trying to downgrade Kotlin version to 1.3.X (if you haven't already) or RoboVM to 2.3.5, since this configuration seemed to work at some point. However, ultimately we shouldn't have to downgrade the dependencies at all - thanks for setting up the issue in RoboVM repository.

I'll leave this issue as open until it is addressed in RoboVM and I'll update the README of `ktx-async`.

**Comment by czyzby** [comment]
By the way, to other developers: if you have managed to run Kotlin coroutines on iOS, please do share your configuration. Thanks.

**Comment by dkimitsa** [comment]
hi, MobiVM maintainer is here. 
code snippet provided in https://github.com/MobiVM/robovm/issues/572 does work for me. 
waiting for complete sample project to test/reproduce. please share if any.
thx && happy coding

**Comment by czyzby** [comment]
@auraxangelic Could you upload a stripped down version of your project to GitHub? Thanks.

@dkimitsa Thanks for the reply. Is it possible that the error is caused by the build target or local project setup? If that helps, Kotllin coroutines were tested through a LibGDX application.

**Comment by dkimitsa** [comment]
@czyzby it might be caused by multi-module project structure. In simple "single view without storyboard" project created from template -- there is no issue. Will test tomorrow on empty libGDX project as well

**Comment by dkimitsa** [comment]
btw, `java.lang.NoClassDefFoundError ` might be caused by aggressive tree shaker, have tested in by test bed and it is not a case.

**Comment by dkimitsa** [comment]
@czyzby yep i'm familiar with the libgdx, will be able to test on sample project tomorrow. But if there is a ready to reproduce project at hand it would be nice to test it

**Comment by dkimitsa** [comment]
@czyzby checked with dummy libgdx project -- works for me:
- iOS + core + desktop project 
- run from Idea 2021.1 EAP
- gradle version 6.8.3
- kotlin/ktx setup in gradle (both core and iOS):
```
plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.4.32'
}
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.3")
}
```
- test code called from java classes : 
```

import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.launch

fun launchCoroutine() {
    GlobalScope.launch {
        println("Running...")
    }
}

class KtxTest {
    fun test() {
        launchCoroutine()
    }
}
```

please share your project that demonstrate the issue. 
thanks

**Comment by czyzby** [comment]
@dkimitsa I see, thanks for checking that out. It might be possible that @auraxangelic local setup is at fault here. The only other thing I could think of is `ktx-async` (our module with coroutines support for LibGDX) somehow interferes with RoboVM. Here's how you can modify the example to launch coroutines via `ktx-async`:

```diff
plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.4.32'
}
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.3")
+   implementation 'io.github.libktx:ktx-async:1.9.14-b1'
}
```

Minimal application adapter code that launches a coroutine:
```kotlin
import com.badlogic.gdx.ApplicationAdapter
import ktx.async.KtxAsync

class MyApp : ApplicationAdapter() {
  override fun create() {
    KtxAsync.initiate()
    KtxAsync.launch {
      println("Executed via coroutine.")
    }
  }
}
```

If you're able to run this without any problems, I think it's safe to say it comes down to local setup. [This post](https://github.com/tommyettinger/gdx-liftoff/issues/42#issuecomment-802888471) includes details on how @auraxangelic set up their environment - might help with pinning down the issue.

**Comment by dkimitsa** [comment]
@czyzby this snippet works as well. probably issue is related to project structure/local setup. a minimal project would be useful

**Comment by czyzby** [comment]
Thanks again for taking the time to test it.

**Comment by auraxangelic** [comment]
I probably should have thought about this before. In LibGDX, there is the ios module and core module. RoboVM is doesn't pick up the transitive dependencies of the core module.

The issue is fixed when I add coroutines as a dependency to the ios module.

**Comment by auraxangelic** [comment]
I've created the default Super Koalio, converted it to kotlin, added a coroutine with with the issue, then added the fixing dependency in a repo. Check out the commits here: https://github.com/auraxangelic/liftoff-koalio/commits/main

You should be able to reproduce the issue by removing the dependency from the ios module.

**Comment by czyzby** [comment]
Glad you worked it out. I'll update documentation of the `ktx-async` module.

**Comment by czyzby** [comment]
@auraxangelic As suggested on the Discord, try setting the coroutines dependency to `api` rather than `implementation`. That should address the issue.

**Comment by tommyettinger** [comment]
> Turns out RoboVM isn't picking up the transitive dependencies of the core module.

This is because you added the dependency on ktx-async using `implementation` in core, which makes that dependency impossible to use transitively. While it's kinda strange, that is the purpose of `implementation`; I believe it is meant to make large projects with many layers of transitive dependencies able to compile and/or autocomplete efficiently by avoiding looking at the `implementation` dependencies of the project's own dependencies. I just generated a liftoff project with no changes to gdx-liftoff or the generated files, specifying ktx-async as a third-party dependency, and it uses `api` to depend on ktx-async in core, which does permit transitive use. Specifically:
```gradle
dependencies {
	api "com.badlogicgames.gdx:gdx:$gdxVersion"
	api "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"
	api "io.github.libktx:ktx-async:$ktxAsyncVersion"
}
```

This explains why the RoboVM devs couldn't reproduce the issue; they were configuring their projects correctly. There's no need to have a separate dependency in the ios module if you use `api` to depend on ktx-async, so I don't think the latest troubleshooting docs are 100% necessary. While many dependencies work fine without needing to be used transitively from ios or lwjgl3 or whatever other module, it looks like ktx-async is used from ios-specific code often, so it should use `api` in the core dependency, letting all the other modules use it too.

**Comment by czyzby** [comment]
@tommyettinger Thanks, that was helpful. I've updated the troubleshooting section to explain the issue a bit better. It's interesting though that desktop and Android projects seemed to pick up the dependency either way.

**Comment by auraxangelic** [comment]
Thanks for looking into this with me. Glad we figured it out!
